# ActiveRecord Database Configuration

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  database: app_production
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  username: root
  password:
  pool: 5
