# ActiveRecord Database Configuration

defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  username: root
  password:
  pool: 5

development:
  database: app_development
  <<: *defaults

test:
  database: app_test
  <<: *defaults

production:
  database: app_production
  <<: *defaults
